### ISSUE TITLE
Inquiry About Internship Project Guidance Regarding Use Of UCSD Historical Enrollment Data

### ISSUE THREAD

**Issue by a2jensen** [ewang2002/ewang2002#3]
Hello Edward!

Hope this email finds you well, I am emailing you to inquire about the UCSD Historical Enrollment Data project regarding the utilization of data.

For context - My name is Angelo and I am currently in a group of 7 people as part of a summer internship program at SDSC(San Diego Supercomputer Center).  Our summer project that we agreed to delve into was recreating a SETS/CAPES like website with added on unique features that would include things such as providing suggestions for each class on if you should first pass or second pass. Also - another project that we are driving inspiration from is sunSETS as well.

I currently serve the role as backend developer and I am in charge of developing the 1st/2nd pass suggestion feature. The current vision for the feature right now is that when you look up a class you will be given all its statistical data(similar to SETS), but alongside with it there will be a tip that will indicate if it is a class you should first pass or second pass indicated by a small sentence. This is the base idea but we are def open to changing it as the project goes along in case we run into any issues.

Before reading through the docs of UCSD Historical Enrollment, our high level vision was to somehow grab the data from the github repo and store it in our own backend, from there we would write up an algorithm/function to determine if the class should be 1st or 2nd passed.

However after looking through the docs and seeing how the files that contain the relevant data for our feature seem to be too large, it seems that some base changes need to be made. I was wondering if you can provide any sort of input or a way in how you would approach this given that you were in charge of the entire historical enrollment project.

Thank you!

**Comment by ewang2002** [comment]
Hi Angelo,

For your use case, you probably need to store all of the data in memory or in a database (e.g., SQLite) of some sort and then query it. That said, I can think of a few ways to reduce the amount of data you'll need to save. 

If the goal is to check if a user should first- or second-pass a class, then the only data you really need is any CSV file in the "overall" folder of the data repository, and the enrollment times for that corresponding term.

Consider Fall 2024: the [overall](https://github.com/UCSD-Historical-Enrollment-Data/2024Fall/tree/main/overall) folder contains the "cleaned" CSV files whose columns are defined by [this part of the documentation](https://github.com/UCSD-Historical-Enrollment-Data/UCSDHistEnrollData/blob/master/docs/csv_info.md#cleaned-csv-files). Each row defines the number of enrolled students, waitlisted students, and seats available at that time. You can figure out when the first- and second-pass dates are from [UCSD's website](https://blink.ucsd.edu/instructors/courses/enrollment/start.html) (we also record the dates in each data repository's README). 

With that in mind, you can filter the data in each "cleaned" CSV file so that the only entries are the ones whose dates are between the start of first pass and the end of second pass (and possibly a week or two before the term starts, which is when you'll see students enrolling in or or dropping classes). This gives you the specific times (e.g., 6/29/2024 at 10:05am) and corresponding data at that time (e.g., 10 people waitlisted, 5 people enrolled, etc. at 6/29/2024 at 10:05am).

If you don't care about the times, then you can further filter the data so that you only have the dates. This might be helpful if you just want to track whether a class fills up after a certain enrollment time (e.g., after sophomore first pass). For this, you have two different approaches:
- for each _day_, only keep the first (i.e., earliest) data point. So, for example, if you have 500 data points for 6/29/2024, then you can just take the earliest one and discard the rest. This is what I believe BerkeleyTime does (see [this example](https://berkeleytime.com/enrollment/0-21743-fall-2024-513825)). You can either do this for each day in _general_, or for each day during first- and second-pass enrollment. 
- for each _day_, take the data point that is the closest to when a new enrollment group starts. For example, if you have 500 data points for sophomore second pass, you can just take the first data point for sophomore second pass. This might make it easier for your algorithm since it's supposed to tell the user if they have a reasonable chance of being able to enroll during a specific enrollment period. 

I imagine the first approach will require the least amount of work. The second approach might require a little more work, but will probably be easier for your algorithm. 

> but alongside with it there will be a tip that will indicate if it is a class you should first pass or second pass indicated by a small sentence

Here's a suggestion: instead of telling the user whether they should first pass or second pass the class, why not just present all the data to them in the form of a readable graph or something similar, and then let the user draw their own conclusion from that? [This is what BerkeleyTime does to some degree](https://berkeleytime.com/enrollment/0-21743-fall-2024-513825&1-21743-fall-2023-470207&2-21743-spring-2023-450423). Considering that enrollment between two terms can be inconsistent (e.g., a class might fill up after first pass in FA23 but hasn't filled up yet in FA24), I think this is probably the better (and easier) approach. 


Let me know what you think.

cc @rybplayer

**Comment by a2jensen** [comment]
Thank you so much! This has helped a ton and I'm definitely gonna be referencing all this when working on this feature. It helped narrow down the information that I needed from the repo and the second approach of optimizing the amount of data being used seems the way that I will be going for.

I also agree with your suggestion and how BerkeleyTime does the feature with displaying all relevant data on a graph, so I will be shifting our original idea to that.

Thank you for your time and our group will definitely reach out for further advice if needed!

**Comment by ewang2002** [comment]
Of course, happy to help.

Please keep me updated on how your project is doing. I would be particularly interested in seeing what the final result looks like.
