### ISSUE TITLE
Enrollment Chart Issue Update - TritonSEA

### ISSUE THREAD

**Issue by a2jensen** [ewang2002/ewang2002#4]
Hello Edward!

I messaged you a couple months ago regarding how I can use the enrollment data to help make an enrollment chart feature for an internship project I was apart of for SDSC. Well, we were able to finish our project called "TritonSEA"!

Here is the website, it is fully deployed:
https://triton-sea.com/

This project is actually still ongoing and it has turned from an internship project to a passion project. Me and most members of the team are still tweaking/working on it and we are planning a beta release(to be announced on reddit really soon!). We will continue to improve and iterate on the website in the future as were confident that this product will be a hit with UCSD students. 

Thank you for the great advice and you help, I ended up using the approach of filtering the files through just grabbing the first enrollment point from each day. This was my first ever software internship so to be able to be apart of a team that made this product was awesome.

Feel free to give your thoughts and any feedback if you can! Once again thanks for the help :)

NOTE: The mobile version is pretty limited and to get the full experience the desktop version is what you want to see.

**Comment by ewang2002** [comment]
Hi Angelo,
I'm glad you guys managed to get the project finished. Took a quick glance at it and it looks great -- better than what I could possibly do 😄.

I'm also super happy that you guys are continuing this project purely for enjoyment. I know it's going to be incredibly helpful for anyone who comes across it (hopefully, you all advertised it on r/ucsd).

Some quick questions:
- is your project open source? I would love to see how you guys implemented everything. 
- how are you guys getting the percentage of students enrolled in a class? Are you guys using the most recent data point, or WebReg's API? 

And some quick feedback on my side:
- regarding the enrollment data, I do ask that you all cite the [parent repository](https://github.com/UCSD-Historical-Enrollment-Data/UCSDHistEnrollData) so anyone else can benefit from using the data. 
- your Discord link appears to be expired. Not sure if that's intentional. 

If you are interested, my friend, @mr4tt, can provide design feedback. You guys can also coordinate with @rybplayer to get the most recent data updated on the repo. 

Thanks again for keeping me updated. I'm proud of you all.

**Comment by a2jensen** [comment]
Thanks,

-> Our project is not currently open source. Right now the repository is apart of the SDSC GitLab repository and only interns can have access. We did make it a goal in the near future to move everything to github so it can be public.
-> We are just using the most recent data point. We didn't work with the WebReg API at all.

I will also make sure to correctly cite and fix the discord link, I'll definitely consider reaching out to the people you referenced as well!

**Comment by ewang2002** [comment]
I'll probably join the Discord in the morning to say hi :) 

I've already told @mr4tt about your project, so she's aware of what's going on. I think she'll just respond here directly. 

@rybplayer might be able to get you some form of (unofficial) API access. I'll have to talk to him and see how that would work. Alternatively, since you have a substantial project, you might be able to talk to the school about getting official API access (maybe start with ITS and see where to go from there).

**Comment by a2jensen** [comment]
Okay 👍 

here's the discord link(I also just updated it to work on the website as well): https://discord.gg/HS2F3n7QJd

**Comment by ewang2002** [comment]
Closing the issue due to inactivity.

Please remember to cite where you got the data you used from. Thanks.
